# GitHub Sponsors funding file
# If you want to enable GitHub Sponsors for this project, uncomment and configure:

# github: yourusername
# patreon: yourpatreon
# open_collective: yourproject
# ko_fi: yourusername
# liberapay: yourusername
# custom: ["https://paypal.me/yourusername"]
