services:
  - type: web
    name: ai-symptom-checker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main_simplified:app --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
